version: '3.9'

services:
  db:
    image: postgres:13.16-bookworm
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-database
      # currently, locale is not working in this image
      # POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
      # LANG: de_DE.UTF-8
      # LC_COLLATE: de_DE.UTF-8
      # LC_CTYPE: de_DE.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d # Mount the host directory with init scripts

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: