### Sign in existing user

POST http://localhost:3000/auth/sign-in HTTP/1.1
content-type: application/json

{
    "username": "harry.weinfurth@example.com",
    "password": "test"
}

#{
#    "username": "john.doe@example.com",
#    "password": "password123"
#}

### Sign up new user

POST http://localhost:3000/auth/sign-up HTTP/1.1
content-type: application/json

{
    "username": "harry.weinfurth@example.com",
    "password": "test"
}

### Check for authorization

GET http://localhost:3000/auth/profile HTTP/1.1
Authorization: Bearer [TOKEN]

### Test for all users

GET http://localhost:3000/users HTTP/1.1

###

GET http://localhost:3000/.well-known/jwks.json HTTP/1.1

###

GET http://localhost:8084/expenses?from=2025-06-02&to=2025-06-30
Authorization: Bearer [TOKEN]

###

POST http://localhost:8084/expenses
Authorization: Bearer [TOKEN]
content-type: application/json

{
    "amount": 78.87,
    "description": "hello fresh",
    "spentAt": "2025-06-03T17:38:16+00:00"
}