POST http://localhost:3000/auth/sign-in HTTP/1.1
content-type: application/json

{
    "username": "John",
    "password": "test"
}

###

POST http://localhost:3000/auth/sign-up HTTP/1.1
content-type: application/json

{
    "username": "John",
    "password": "test"
}

###

GET http://localhost:3000/auth/profile HTTP/1.1
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4iLCJzdWIiOjEsImlhdCI6MTczMDkzMjMxNCwiZXhwIjoxNzMwOTMyNTU0fQ.Y5vrR81WSCvXTBEdSfrxJv6g60GavnN-2F8qvZugF0A"

###
