POST http://localhost:3000/auth/sign-in HTTP/1.1
content-type: application/json

{
    "username": "John",
    "password": "test"
}

###

POST http://localhost:3000/auth/sign-up HTTP/1.1
content-type: application/json

{
    "username": "John",
    "password": "test"
}

###